CREATE OR REPLACE STREAM Album_Changes_Stream ON TABLE RAW_ALBUM
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Artist_Changes_Stream ON TABLE RAW_ARTIST
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Customer_Changes_Stream ON TABLE RAW_CUSTOMER
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Employee_Changes_Stream ON TABLE RAW_EMPLOYEE
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Genre_Changes_Stream ON TABLE RAW_GENRE
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Invoice_Changes_Stream ON TABLE RAW_INVOICE
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM InvoiceLine_Changes_Stream ON TABLE RAW_INVOICELINE
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM MediaType_Changes_Stream ON TABLE RAW_MEDIATYPE
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Playlist_Changes_Stream ON TABLE RAW_PLAYLIST
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM PlaylistTrack_Changes_Stream ON TABLE RAW_PLAYLISTTRACK
   APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM Track_Changes_Stream ON TABLE RAW_TRACK
   APPEND_ONLY = TRUE;